### ISSUE TITLE
Missing cDAI (currently only cSAI contract)

### ISSUE THREAD

**Issue by mirshko** [NoahZinsmeister/hypertext#2]
Seems while the UI shows cDAI its actually cSAI still! 

https://etherscan.io/token/0xF5DCe57282A584D2746FaF1593d3121Fcac444dC?a=0xf6fDeE29e3A14610fdbE187e2d3442543cfA45B8

Need to update the contracts. :)

**Comment by NoahZinsmeister** [comment]
thanks! closed via https://github.com/NoahZinsmeister/hypertext/commit/40783cd48daa31e466fa6261669c007c2701be9d
